name: Build and Push (dev)

on:
  push:
    branches: [dev]

jobs:
  build-push:
    uses: muri1o/pipelines/.github/workflows/build-push.yml@main
    with:
      image: muri1o/whatsapp-bot
    secrets: inherit
